INSERT INTO users (name, email, framework) VALUES ('mkyong', 'mkyong@gmail.com', 'Spring MVC, GWT');
INSERT INTO users (name, email, framework) VALUES ('alex', 'alex@yahoo.com', 'Spring MVC, PLAY');
INSERT INTO users (name, email, framework) VALUES ('joel', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel1', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel2', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel3', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel4', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel5', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel6', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel7', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel8', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel9', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel10', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel11', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel12', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel13', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel14', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel15', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel16', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel17', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel18', 'joel@gmail.com', 'Spring MVC, JSF 2');
INSERT INTO users (name, email, framework) VALUES ('joel19', 'joel@gmail.com', 'Spring MVC, JSF 2');